### PR TITLE
ST-120 added user-settings table field

### PR DESCRIPTION
**Pull request by lab900-gino-vanhoudt**
@Senn: 2 remarks about the CSS
- is the use of ::ng-deep ok? or should i move it to a main css file? (if so, is that the _theming.scss file?)
- i noticed for merger and action-button-toggle, there is some separate scss files, i think for changing styling in the project where you use it. is that something to consider here too?

### CODE REVIEW

**Comment by lab900-gino-vanhoudt** [comment]
screenshot: 
image

**Comment by lab900-senn-lambrecht** [comment]
@lab900-gino-vanhoudt 

**is the use of ::ng-deep ok? or should i move it to a main css file?** 
-> for me it's fine to use it for now, as we still use it in other places. But I know Angular is planning on removing the support for it so it would be good if we can avoid it. 

**i noticed for merger and action-button-toggle, there is some separate scss files, i think for changing styling in the project where you use it. is that something to consider here too?**
-> You can add a new files in the scss folder for specific components (with the same mixin structure). Don't forget to import them in the _theming.scss. This is indeed for project styling -> https://material.angular.io/guide/theming-your-components

**Comment by senn** [comment]
please tag "Senn" correctly next time :-)

**Comment by lab900-gino-vanhoudt** [comment]
@lab900-senn-lambrecht (last tag was from Intellij, that's why it didn't work)
- I don't think there is theming that needs to be updated from an outside project, so I'll leave the mixing theming for what it is
- resolved merge conflicts

**Review by lab900-senn-lambrecht — APPROVED** [review]

**Pull request merged**
